### PR TITLE
Booster enabled flag

### PR DESCRIPTION
**Pull request by phylake**
## Changelog

Added `BOOSTER_ENABLED` to the fleet units

## Notes

Did you introduce any command that executes `docker run`? **No**

If you did, have you ensured that all your `docker run` using the default logger have either `max-size` and/or `max-file` set? **N/A**

Are there any dependencies on github.com/adobe-platform/infrastructure? **No**

### CODE REVIEW

**Comment by matthewdfuller** [comment]
👍 but is there an `infrastructure` repo component with this that adds the booster enabled config to the configs section in `/v2/configs/example-stack-all/serets.json`?

**Comment by phylake** [comment]
@matthewdfuller No there isn't. It would be a similar override as BootstrapCommand, right? Can you point me to the relevant pieces so I can hook it up?

**Comment by matthewdfuller** [comment]
@phylake sort of, but this is overriding the default for `/booster/config/enabled 0` which you set in `001-defaults.sh` in this PR. If the user wants to enable booster, I'm assuming they'd have to set that to 1, which should be provided as an example here:

https://github.com/adobe-platform/infrastructure/blob/master/v2/config/example-stack-all/secrets-example.json#L74

Just add a line to that configs section:

```
"/booster/config/enabled": "1"
```

**Comment by phylake** [comment]
@matthewdfuller Oh I never made the connection that those config values were overrides to etcd keys. Magical! I'll add that now

**Comment by matthewdfuller** [comment]
Cool, thanks! I'll merge this in in the meantime

**Comment by phylake** [comment]
@matthewdfuller https://github.com/adobe-platform/infrastructure/pull/121

**Pull request merged**
