### PR TITLE
Changes to Journal-Pipe Service for SPLUNK ES

### PR DESCRIPTION
**Pull request by ts3ng**
PER ISSUE: https://github.com/adobe-community/issues-ethos/issues/1251
## Changelog
1. add aws account number requested by splunkES group
2. fixed instanceid to not me ami-id
3. fixed hostname
4. restructured common setup files for splunk
5. moved environment variable declaration to be in /etc/splunk.env file instead of in fleet. 
6. cleaned up journald-splunk-pipe fleet unit definition.

## Notes

You must explain how any `docker run` executions your PR introduces handles log accumulation. 

Did you introduce any command that executes `docker run`?
No
Are there any dependencies on github.com/adobe-platform/infrastructure?
No
If so:
 
Is an update to the base stack required(rare)?
No
Is an A/B required?
Yes, unles syou reload fleet units manually.
Are you dependent on new secrets, or infrastructure in any way?
No

…setup, make setup naming more consistent

### CODE REVIEW

**Comment by ts3ng** [comment]
I just got pinged by the ops team they want to hold off on the merge until i get some more verification from the splunk ES team.  They wanted to send.

**Comment by manojbadam** [comment]
@ts3ng : can we add the role info (control, worker, proxy) which tier the host relates to. This could help us in filtering logs.

**Comment by ts3ng** [comment]
@manojbadam sure i can add it, but the STACK_NAME which already has it also gives the role as well it also gives if it's the AorB cluster. 
here is the example of what a log looks like in the current state.
'''
STACK_NAME=booster-sandbox-ue1-logging-b ACCOUNTID=258057316678 INSTANCEID=i-08c1ba7f2c9a612ae HOSTNAME=ip-10-74-253-70.ec2.internal LOG=Sep 15 10:40:50 ip-10-74-253-70.ec2.internal docker[940]: INFO:root:{"app:":"applicationdef1.imagedef","index":"test-index","message":"TEST MESSAGE","sourceytype":"json","volume":"high"}
'''

**Comment by ts3ng** [comment]
closing this request replacing with https://github.com/adobe-platform/ethos-systemd/pull/83 instead which includes more changes.

**Pull request closed without merging**
